#!/bin/bash

# configuration of buildling process

# object extension
OBJ_EXT='o'
# select which compiler to use
COMMAND=ar
# send flags to compiler
COMMAND_FLAG='-rs'
TARGET='garage'

source ./build_util

function link_error {
	echo "ERROR: Failed to link"
	exit 1
}
